
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -61;
const int acc_off_y = -100;
const int acc_off_z = -213;
const float acc_scale_x = 3703.533072;
const float acc_scale_y = 4295.587561;
const float acc_scale_z = 4137.834620;

const int magn_off_x = -58;
const int magn_off_y = -18;
const int magn_off_z = 21;
const float magn_scale_x = 523.171345;
const float magn_scale_y = 546.993532;
const float magn_scale_z = 536.046182;
